@IdentityProvider.HostAddress = http://localhost:8080

# get client credentials token
# Authorization is Base64 for payment-gateway:EKZZOAmSQwnH1y4xerd5Zkf2hfLobpmD
POST {{IdentityProvider.HostAddress}}/realms/fraud-api/protocol/openid-connect/token HTTP/1.1
Host: authorization-server.com
Authorization: Basic cGF5bWVudC1nYXRld2F5OkVLWlpPQW1TUXduSDF5NHhlcmQ1WmtmMmhmTG9icG1E
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
