@IdentityProvider.HostAddress = http://localhost:8080

### Get OAuth2 Token for Payment Gateway using username/password

POST {{IdentityProvider.HostAddress}}/realms/payment-gateway/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=payment-gateway-customer&scope=email%20openid&username=test@test.com&password=123
